In [10]:
import numpy as np
import copy

In [37]:
def read(filename):
    start = open(filename,'r').read().replace('\n', '').replace(' ', '')
    goal = open('goal.txt','r').read().replace('\n', '').replace(' ', '')
    start_state = []
    goal_state = []
    for i in range(0,len(start)):
        start_state.append(int(start[i]))
    for i in range(0,len(goal)):
        goal_state.append(int(goal[i]))
    return start_state, goal_state


In [ ]:
class Position:
    def __init__(self, index):
        self.x = index // 3
        self.y = index % 3

In [47]:
class State2:
    def __init__(self, state, next_step = None):
        self.state = np.array([state[:3], state[3:6], state[6:]])
        self.next_step = next_step
        self.FindZero()

    def __eq__(self, other):
        if type(self) == type(other) and self.state.all() == other.state.all():
            return True
        else:
            return False
        
    def Print(self):
        print(self.state)
        print('---------')
    
    def FindZero(self):
        index = np.where(self.state == 0)
        coordinate= list(zip(index[0], index[1]))
        return coordinate[0]

    def SavedMove(self,dir=None):
        if (self.ValidMove(dir)):
            old = copy.deepcopy(self)
            if dir == 'right':
                target = [self.FindZero()[0], self.FindZero()[1] + 1]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                return old
            if dir == 'left':
                target = [self.FindZero()[0], self.FindZero()[1] - 1]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                return old
            if dir == 'up':
                target = [self.FindZero()[0] - 1, self.FindZero()[1]]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                return old
            if dir == 'down':
                target = [self.FindZero()[0] + 1, self.FindZero()[1]]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                return old
                
    def ValidMove(self, dir=None):
        if dir == None:
            return False
        elif dir == 'right':
            if self.FindZero()[1] != 2:
                return True
        elif dir == 'left':
            if self.FindZero()[1] != 0:
                return True
        elif dir == 'up':
            if self.FindZero()[0] != 0:
                return True
        elif dir == 'down':
            if self.FindZero()[0] != 2:
                return True
        else:
            return False

In [50]:
start_state, goal_state = read('input.txt')
start = State2(start_state)
start.Print()
start.SavedMove('down')
start.Print()
start.SavedMove('up')
start.Print()

[[7 2 4]
 [5 0 6]
 [8 3 1]]
---------
[[7 2 4]
 [5 3 6]
 [8 0 1]]
---------
[[7 2 4]
 [5 3 6]
 [8 0 1]]
---------


In [ ]:
class State:
    def __init__(self, state, next_step = None):
        self.state = state
        self.next_step = next_step
    def __eq__(self, other):
        if type(self) == type(other) and self.state == other.state:
            return True
        else:
            return False
    def Print(self):
        array = np.array([self.state[:3], self.state[3:6], self.state[6:]])
        for item in array:
            print(item)
