In [ ]:
import numpy as np
import copy
from IPython.display import clear_output
import time

In [ ]:
def read(filename):
    start = open(filename,'r').read().replace('\n', '').replace(' ', '')
    goal = open('goal.txt','r').read().replace('\n', '').replace(' ', '')
    start_state = []
    goal_state = []
    for i in range(0,len(start)):
        start_state.append(int(start[i]))
    for i in range(0,len(goal)):
        goal_state.append(int(goal[i]))
    return start_state, goal_state

In [ ]:
class State2:
    def __init__(self, state, pre_move = None):
        self.state = np.array([state[:3], state[3:6], state[6:]])
        self.pre_move = pre_move
        self.FindZero()

    def Print(self):
        print(self.state)
        print(self.pre_move)
        print('---------')
        # clear_output(wait=True)
        # time.sleep(10)
    
    def FindZero(self):
        index = np.where(self.state == 0)
        coordinate= list(zip(index[0], index[1]))
        return coordinate[0]
    
    def ValidMove(self, move=None):
        if move == None:
            return False
        elif move == 'right':
            if self.FindZero()[1] != 2:
                return True
        elif move == 'left':
            if self.FindZero()[1] != 0:
                return True
        elif move == 'up':
            if self.FindZero()[0] != 0:
                return True
        elif move == 'down':
            if self.FindZero()[0] != 2:
                return True
        else:
            return False

    def SavedMove(self, move=None):
        if (self.ValidMove(move)):
            old = copy.deepcopy(self)
            if move == 'right':
                target = [self.FindZero()[0], self.FindZero()[1] + 1]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
            elif move == 'left':
                target = [self.FindZero()[0], self.FindZero()[1] - 1]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
            elif move == 'up':
                target = [self.FindZero()[0] - 1, self.FindZero()[1]]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
            elif move == 'down':
                target = [self.FindZero()[0] + 1, self.FindZero()[1]]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
        else:
            return False
    
    def CopyMove(self, move=None):
        if (self.ValidMove(move)):
            temp = copy.deepcopy(self)
            if move == 'right':
                target = [temp.FindZero()[0], temp.FindZero()[1] + 1]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
            elif move == 'left':
                target = [temp.FindZero()[0], temp.FindZero()[1] - 1]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
            elif move == 'up':
                target = [temp.FindZero()[0] - 1, temp.FindZero()[1]]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
            elif move == 'down':
                target = [temp.FindZero()[0] + 1, temp.FindZero()[1]]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
        else:
            return False
    
    def Expand(self):
        child_node = []
        next_move = ['up','down','left','right']
        for i in range(0,4):
            if (self.CopyMove(next_move[i]) != False):
                child_node.append(self.CopyMove(next_move[i]))
        return child_node

    

In [ ]:
def searched(searched_set,state):
    for i in searched_set:
        if state == i:
            return True
    return False

searchedSet =[]
def DFS(state, end_state, depth):
    global searchedSet

    if searched(searchedSet,state):
        return False
    
    searchedSet.append(state)

    if depth == 0:
        if state == end_state:
            state.Print()
            return True
    else:
        for nodes in state.Expand():
            nodes.Print()
            found = DFS(nodes,end_state,depth-1)
            if found:
                print(found)
                return True
            
    searchedSet.remove(state)
    return False


In [20]:
start_state, goal_state = read('input.txt')

start = State2(start_state)
end = State2(goal_state)

for i in start.Expand():
    i.Print()
# DFS(start,end,2)

[[7 2 4]
 [5 0 6]
 [8 3 1]]
None
---------
[[7 0 4]
 [5 2 6]
 [8 3 1]]
up
---------
[[7 2 4]
 [5 0 6]
 [8 3 1]]
down
---------
[[7 2 4]
 [0 5 6]
 [8 3 1]]
left
---------
