In [10]:
import numpy as np
import copy

In [37]:
def read(filename):
    start = open(filename,'r').read().replace('\n', '').replace(' ', '')
    goal = open('goal.txt','r').read().replace('\n', '').replace(' ', '')
    start_state = []
    goal_state = []
    for i in range(0,len(start)):
        start_state.append(int(start[i]))
    for i in range(0,len(goal)):
        goal_state.append(int(goal[i]))
    return start_state, goal_state


In [ ]:
class Position:
    def __init__(self, index):
        self.x = index // 3
        self.y = index % 3

In [96]:
class State2:
    def __init__(self, state, pre_move = None):
        self.state = np.array([state[:3], state[3:6], state[6:]])
        self.pre_move = pre_move
        self.FindZero()

    def __eq__(self, other):
        if type(self) == type(other) and self.state.all() == other.state.all():
            return True
        else:
            return False
        
    def Print(self):
        print(self.state)
        print('---------')
    
    def FindZero(self):
        index = np.where(self.state == 0)
        coordinate= list(zip(index[0], index[1]))
        return coordinate[0]
    
    def ValidMove(self, move=None):
        if move == None:
            return False
        elif move == 'right':
            if self.FindZero()[1] != 2:
                return True
        elif move == 'left':
            if self.FindZero()[1] != 0:
                return True
        elif move == 'up':
            if self.FindZero()[0] != 0:
                return True
        elif move == 'down':
            if self.FindZero()[0] != 2:
                return True
        else:
            return False

    def SavedMove(self, move=None):
        if (self.ValidMove(move)):
            old = copy.deepcopy(self)
            if move == 'right':
                target = [self.FindZero()[0], self.FindZero()[1] + 1]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
            elif move == 'left':
                target = [self.FindZero()[0], self.FindZero()[1] - 1]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
            elif move == 'up':
                target = [self.FindZero()[0] - 1, self.FindZero()[1]]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
            elif move == 'down':
                target = [self.FindZero()[0] + 1, self.FindZero()[1]]
                self.state[self.FindZero()[0]][self.FindZero()[1]] = self.state[target[0]][target[1]]
                self.state[target[0]][target[1]] = 0
                self.pre_move = move
                return old
        else:
            return False
    
    def CopyMove(self, move=None):
        if (self.ValidMove(move)):
            temp = copy.deepcopy(self)
            if move == 'right':
                target = [temp.FindZero()[0], temp.FindZero()[1] + 1]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
            elif move == 'left':
                target = [temp.FindZero()[0], temp.FindZero()[1] - 1]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
            elif move == 'up':
                target = [temp.FindZero()[0] - 1, temp.FindZero()[1]]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
            elif move == 'down':
                target = [temp.FindZero()[0] + 1, temp.FindZero()[1]]
                temp.state[temp.FindZero()[0]][temp.FindZero()[1]] = temp.state[target[0]][target[1]]
                temp.state[target[0]][target[1]] = 0
                temp.pre_move = move
                return temp
        else:
            return False
    
    def Expand(self):
        child_node = []
        zero_pos = [self.FindZero()[0], self.FindZero()[1]]
        next_move = ['right','left','up','down']
        checker = ['left','right','down','up']
        for i in range(0,4):
            if (self.pre_move != checker[i] and self.CopyMove(next_move[i]) != False):
                child_node.append(self.CopyMove(next_move[i]))
        return child_node

        


        
    

In [ ]:
def DFS(state, depth):
    

In [99]:
start_state, goal_state = read('input.txt')

start = State2(start_state)
start.Print()

node = start.Expand()

for i in node:
    i.Print()


[[7 2 4]
 [5 0 6]
 [8 3 1]]
---------
[[7 2 4]
 [5 6 0]
 [8 3 1]]
---------
[[7 2 4]
 [0 5 6]
 [8 3 1]]
---------
[[7 0 4]
 [5 2 6]
 [8 3 1]]
---------
[[7 2 4]
 [5 3 6]
 [8 0 1]]
---------


In [ ]:
class State:
    def __init__(self, state, next_step = None):
        self.state = state
        self.next_step = next_step
    def __eq__(self, other):
        if type(self) == type(other) and self.state == other.state:
            return True
        else:
            return False
    def Print(self):
        array = np.array([self.state[:3], self.state[3:6], self.state[6:]])
        for item in array:
            print(item)
