### COMP3270 A3 (Edmund Tsang 3035667261)

Imports

In [153]:
import io
import sklearn
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

Version check

In [154]:
print(sklearn.__version__)
print(np.__version__)
print(pd.__version__)

1.2.2
1.23.4
1.5.0


Google Colab upload

In [ ]:
from google.colab import files
uploaded = files.upload()

### Mushroom Dataset

Import data

In [143]:
# mushrooms = pd.read_csv('./mushroom.csv', header=None) #for non google colab
mushrooms = pd.read_csv(io.BytesIO(uploaded['mushroom.csv']), header=None) #for google colab
print(mushrooms.shape)
mushrooms.head()

(8124, 23)


0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

Transform categorical data into numbers

In [144]:
for col in mushrooms.columns.values:
    #Define a new LabelEncoder() function named le
    le = preprocessing.LabelEncoder()
    #give a number for each unique labe
    le_fitted = le.fit(list(mushrooms[col].unique()))
    #transform the entire column in the mapping
    mushrooms[col] = le_fitted.transform(list(mushrooms[col].values))
    
mushrooms.head()


0   1   2   3   4   5   6   7   8   9   ...  13  14  15  16  17  18  19  \
0   1   5   2   4   1   6   1   0   1   4  ...   2   7   7   0   2   1   4   
1   0   5   2   9   1   0   1   0   0   4  ...   2   7   7   0   2   1   4   
2   0   0   2   8   1   3   1   0   0   5  ...   2   7   7   0   2   1   4   
3   1   5   3   8   1   6   1   0   1   5  ...   2   7   7   0   2   1   4   
4   0   5   2   3   0   5   1   1   0   4  ...   2   7   7   0   2   1   0   

   20  21  22  
0   2   3   5  
1   3   2   1  
2   3   2   3  
3   2   3   5  
4   3   0   1  

[5 rows x 23 columns]

Split the data into traning set and testing set

In [145]:
x_train, x_test, y_train, y_test = train_test_split(mushrooms.values[0:,1:23], mushrooms.values[0:,0], test_size=0.25, shuffle=True)
print (x_train[0:5])
print (y_train[0:5])

[[2 2 4 0 8 1 0 1 0 1 0 1 1 6 7 0 2 1 0 7 4 2]
 [0 0 8 0 5 1 1 0 2 0 0 1 2 7 7 0 2 2 4 7 3 1]
 [2 0 3 0 2 1 0 0 3 0 1 1 1 0 0 0 2 1 2 1 4 4]
 [5 2 3 0 1 1 0 1 5 0 1 2 2 7 7 0 2 1 4 2 3 0]
 [2 3 4 1 5 1 0 0 9 1 1 2 2 7 6 0 2 1 4 3 5 0]]
[1 0 1 1 0]


#### Using sklearn decision tree package for training

In [146]:
# define a new classifier clf
clf = tree.DecisionTreeClassifier()
# perform training
clf = clf.fit(x_train, y_train)
# perform testing
y_predict = clf.predict(x_test)
# calculate accuracy
print ("Accuracy : ", accuracy_score(y_test, y_predict) * 100)

Accuracy :  100.0


#### Using Naive Bayes with Gaussian distribution

In [147]:
# define a new classifier clf
NB_clf = GaussianNB()
# perform testing
NB_clf.fit(x_train, y_train)
# calculate accuracy
y_predict = NB_clf.predict(x_test)
print ("Accuracy : ", accuracy_score(y_test, y_predict) * 100)

Accuracy :  91.87592319054653


### Breast Cancer (Wisconson) Datase

import data

In [148]:
uploaded = files.upload()
# cancer = pd.read_csv('./breast.csv', header=None) #for non google colab
cancer = pd.read_csv(io.BytesIO(uploaded['breast.csv']), header=None) #for google colab
print(cancer.shape)
cancer.head()

(699, 11)


0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

Drop the first column and convert all data into numbers

In [149]:
#Drop the first column
cancer = cancer.drop(cancer.columns[[0]], axis=1)
#Convert all coulme to int

for col in cancer.columns.values:
    #Define a new LabelEncoder() function named le
    le = preprocessing.LabelEncoder()
    #give a number for each unique labe
    le_fitted = le.fit(list(cancer[col].unique()))
    #transform the entire column in the mapping
    cancer[col] = le_fitted.transform(list(cancer[col].values))

cancer.head()

1   2   3   4   5   6   7   8   9   10
0   4   0   0   0   1   0   2   0   0   0
1   4   3   3   4   6   1   2   1   0   0
2   2   0   0   0   1   2   2   0   0   0
3   5   7   7   0   2   4   2   6   0   0
4   3   0   0   2   1   0   2   0   0   0

Split the data into traning set and testing set

In [150]:
# print(cancer.values[0:,0:9]) #attribute
# print(cancer.values[0:,9]) #class
x_train, x_test, y_train, y_test = train_test_split(cancer.values[0:,0:9], cancer.values[0:,9], test_size=0.25, shuffle=True)
print (x_train[0:5])
print (y_train[0:5])

[[1 0 0 0 1 0 2 0 0]
 [2 0 0 0 1 0 2 0 0]
 [2 0 0 2 7 0 4 7 0]
 [2 0 0 0 1 0 0 0 0]
 [9 9 9 9 9 0 7 7 7]]
[0 0 0 0 1]


#### Using Naive Bayes with Gaussian distribution

In [151]:
#perform the Naive Bayes algorithm 10 times and get the average accuracy with 2 decimal places
itr = 10
result = []
for i in range(itr):
    x_train, x_test, y_train, y_test = train_test_split(cancer.values[0:,0:9], cancer.values[0:,9], test_size=0.25, shuffle=True)
    NB_clf = GaussianNB()
    NB_clf.fit(x_train, y_train)
    y_predict = NB_clf.predict(x_test)
    result.append(accuracy_score(y_test, y_predict) * 100)
print (f"Average {itr} Times Accuracy : ", round(np.mean(result), 2))

Average 10 Times Accuracy :  96.11


#### Using K-NN classification with k = 1, 3, 5, 7

In [152]:
#perform the K-NN algorithm with k = 1,3,5,7 (each 10 times) and get the average accuracy with 2 decimal places
itr = 10
result = []
k_value = [1,3,5,7]
for k in k_value:
    result.clear()
    for i in range(itr):
        x_train, x_test, y_train, y_test = train_test_split(cancer.values[0:,0:9], cancer.values[0:,9], test_size=0.25, shuffle=True)
        KNN_clf = KNeighborsClassifier(n_neighbors=k)
        KNN_clf.fit(x_train, y_train)
        y_predict = KNN_clf.predict(x_test)
        result.append(accuracy_score(y_test, y_predict) * 100)
    print (f"Average {itr} Times Accuracy for k={k} : ", round(np.mean(result), 2))

Average 10 Times Accuracy for k=1 :  93.94
Average 10 Times Accuracy for k=3 :  96.23
Average 10 Times Accuracy for k=5 :  96.23
Average 10 Times Accuracy for k=7 :  95.49
