### COMP3270 A3 (Edmund Tsang 3035667261)

Imports

In [9]:
import sklearn
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [10]:
print(sklearn.__version__)
print(np.__version__)
print(pd.__version__)

1.2.2
1.23.4
1.5.0


Import data

In [11]:
mushrooms = pd.read_csv('./mushroom.csv')
print(mushrooms.shape)
mushrooms.head()

(8123, 23)


p  x  s  n  t p.1  f  c n.1  k  ... s.2  w w.1 p.2 w.2  o p.3 k.1 s.3  u
0  e  x  s  y  t   a  f  c   b  k  ...   s  w   w   p   w  o   p   n   n  g
1  e  b  s  w  t   l  f  c   b  n  ...   s  w   w   p   w  o   p   n   n  m
2  p  x  y  w  t   p  f  c   n  n  ...   s  w   w   p   w  o   p   k   s  u
3  e  x  s  g  f   n  f  w   b  k  ...   s  w   w   p   w  o   e   n   a  g
4  e  x  y  y  t   a  f  c   b  n  ...   s  w   w   p   w  o   p   k   n  g

[5 rows x 23 columns]

Transform categorical data into numbers

In [12]:
for col in mushrooms.columns.values:
    #Define a new LabelEncoder() function named le
    le = preprocessing.LabelEncoder()
    #give a number for each unique labe
    le_fitted = le.fit(list(mushrooms[col].unique()))
    #transform the entire column in the mapping
    mushrooms[col] = le_fitted.transform(list(mushrooms[col].values))
    
mushrooms.head()


p  x  s  n  t  p.1  f  c  n.1  k  ...  s.2  w  w.1  p.2  w.2  o  p.3  k.1  \
0  0  5  2  9  1    0  1  0    0  4  ...    2  7    7    0    2  1    4    3   
1  0  0  2  8  1    3  1  0    0  5  ...    2  7    7    0    2  1    4    3   
2  1  5  3  8  1    6  1  0    1  5  ...    2  7    7    0    2  1    4    2   
3  0  5  2  3  0    5  1  1    0  4  ...    2  7    7    0    2  1    0    3   
4  0  5  3  9  1    0  1  0    0  5  ...    2  7    7    0    2  1    4    2   

   s.3  u  
0    2  1  
1    2  3  
2    3  5  
3    0  1  
4    2  1  

[5 rows x 23 columns]

Split the data into traning set and testing set

In [13]:
x_train, x_test, y_train, y_test = train_test_split(mushrooms.values[0:,1:23], mushrooms.values[0:,0], test_size=0.25, shuffle=True)
print (x_train[0:5])
print (y_train[0:5])

[[5 0 3 1 5 1 0 0 5 1 1 2 2 6 7 0 2 1 4 3 5 0]
 [2 3 3 1 5 1 0 0 7 1 1 2 2 6 7 0 2 1 4 3 5 0]
 [2 3 3 1 5 1 0 0 9 1 1 2 2 6 7 0 2 1 4 3 5 0]
 [0 2 8 1 0 1 0 0 2 0 2 2 2 7 7 0 2 1 4 3 3 1]
 [2 2 3 0 5 1 1 0 3 1 3 0 2 7 7 0 2 1 0 3 3 1]]
[0 0 0 0 0]


#### Using sklearn decision tree package for training

In [14]:
# define a new classifier clf
clf = tree.DecisionTreeClassifier()
# perform training
clf = clf.fit(x_train, y_train)
# perform testing
y_predict = clf.predict(x_test)
# calculate accuracy
print ("Accuracy : ", accuracy_score(y_test, y_predict) * 100)

Accuracy :  100.0


#### Using Naive Bayes with Gaussian distribution

In [15]:
# define a new classifier cl
NB_clf = GaussianNB()
# perform testing
NB_clf.fit(x_train, y_train)
# calculate accuracy
y_predict = NB_clf.predict(x_test)
print ("Accuracy : ", accuracy_score(y_test, y_predict) * 100)

Accuracy :  91.77744953225012
